### ISSUE TITLE
Some files are unknown

### ISSUE THREAD

**Issue by simogaspa84** [tobozo/ESP32-ENC28J60#1] opened 2022-10-11 14:18 UTC
Hi @tobozo i finally have time to test this lib.. 

I am working under platformio with arduino framework..   framework = arduino

Some of the files you added in the folder src are not present..  

![image](https://user-images.githubusercontent.com/12874425/195116533-818666ab-050c-4940-9675-5bcd809ddc06.png)

![image](https://user-images.githubusercontent.com/12874425/195116917-f39b9ff8-a35c-4f16-a45f-884645ac470d.png)

How did you try this repo ? 
Under platformio ? 

Thanks a lot for your support

**Comment by tobozo** [comment] 2022-10-11 15:55
Hi,

this library is for espressif32 package 2.0.5 only, you'll have to force platformio to use it, or use Arduino IDE.

```ini
platform = espressif32 @ ^5
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/2.0.5/esp32-2.0.5.zip
```

closing this as not a bug

**Closed as completed by tobozo** 2022-10-11 15:55 UTC

**Comment by simogaspa84** [comment] 2022-10-11 16:40
ok so this setting should work 

`platform = espressif32@3.5.0
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduinoesp32/releases/download/2.0.5/esp32-2.0.5.zip
board = esp32dev
framework = arduino`

**Comment by tobozo** [comment] 2022-10-11 16:45
I've pushed a platformio example and also published the library to the platformio registry, should be easier now

**Comment by simogaspa84** [comment] 2022-10-11 16:51
Thanks @tobozo  ... I have tried in this way but still I have many errors about the missing files 

```ini
[env:esp32dev]
platform = espressif32@3.5.0
board = esp32dev
framework = arduino
check_tool = cppcheck
check_flags = cppcheck: --enable=all --language=c++ --addon=misra.json
lib_ldf_mode = deep
lib_deps = 
	me-no-dev/AsyncTCP@^1.1.1
	me-no-dev/ESP Async WebServer@^1.2.3
	emelianov/modbus-esp8266@^4.0.0
	bblanchon/ArduinoJson@^6.19.2
	https://github.com/maxgerhardt/EthernetENC.git
	knolleary/PubSubClient@^2.8
	khoih-prog/Functional-Vlpp@~1.0.2
	chrisjoyce911/esp32FOTA@^0.2.3
	ESP32-ENC28J60
```

**Comment by tobozo** [comment] 2022-10-11 18:44
you get errors because you chose to ignore my suggestions of using custom `platform` and `platform_packages` values in your platformio environment.

just try this [platformio example](https://github.com/tobozo/ESP32-ENC28J60/tree/main/examples/pio_example) **as it is** to confirm you're still getting errors.

on the other hand if the platformio example works then the problem comes from your project and I'm afraid it's up to you to fix it
